class SocketEvent {
  static const CREATE_QUIZ_CSS = 'CREATE_QUIZ_CSS';
  static const CREATE_QUIZ_SSC = 'CREATE_QUIZ_SSC';

  static const JOIN_ROOM_CSS = 'JOIN_ROOM_CSS';
  static const JOIN_ROOM_SSC = 'JOIN_ROOM_SSC';

  static const LEAVE_ROOM_CSS = 'LEAVE_ROOM_CSS';
  static const LEAVE_ROOM_SSC = 'LEAVE_ROOM_SSC';

  static const STATISTICAL_ROOM_SSC = 'STATISTICAL_ROOM_SSC';

  static const START_QUIZ_CSS = 'START_QUIZ_CSS';
  static const START_QUIZ_SSC = 'START_QUIZ_SSC';

  static const ANSWER_THE_QUESTION_CSS = 'ANSWER_THE_QUESTION_CSS';
  static const ANSWER_THE_QUESTION_SSC = 'ANSWER_THE_QUESTION_SSC';

  static const TAKE_THE_QUESTION_CSS = 'TAKE_THE_QUESTION_CSS';
  static const TAKE_THE_QUESTION_SSC = 'TAKE_THE_QUESTION_SSC';
}
